<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>8.0.0</VersionPrefix>
    <VersionSuffix Condition="'$(Configuration)'=='Debug'">build$([System.DateTime]::UtcNow.ToString(`yyyyMMddHHmm`))</VersionSuffix>
    <Company>Limbo</Company>
    <Authors>Anders Bjerner</Authors>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
    <Title>Limbo Migrations Redirects API</Title>
    <Product>Limbo Migrations</Product>
  </PropertyGroup>

  <!-- Information for the NuGet package -->
  <PropertyGroup>
    <PackageId>Limbo.Umbraco.Migrations.RedirectsApi</PackageId>
    <PackageTags>Limbo, Umbraco, Migrations, Redirects</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/limbo-works/Limbo.Umbraco.Migrations.RedirectsApi</PackageProjectUrl>
    <PackageIcon>Limbo.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/limbo-works/Limbo.Umbraco.Migrations.RedirectsApi</RepositoryUrl>
  </PropertyGroup>

  <!-- Include dependencies -->
  <ItemGroup>
    <Reference Include="System.Web" />
    <PackageReference Include="Limbo.Umbraco.MigrationsApi" Version="8.0.3" />
    <PackageReference Include="Skybrud.Umbraco.Redirects" Version="2.1.6" PrivateAssets="All" />
    <PackageReference Include="UmbracoCms.Core" Version="[8.6.0,9.0)" />
    <PackageReference Include="UmbracoCms.Web" Version="[8.6.0,9.0)" />
  </ItemGroup>

  <!-- Include package icon and README for the NuGet -->
  <ItemGroup>
    <Content Include="../build/Limbo.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>